#! /usr/bin/env php

<?php

use Paracall\Application\ParacallApp;
use Paracall\Commands\MigrateCommand;
use Paracall\Commands\SayHelloCommand;



require 'vendor/autoload.php';

$app = new ParacallApp('Paracall Igor', '1.0');

$app->setBaseDir(__DIR__);

$app->add(new SayHelloCommand());
$app->add(new MigrateCommand($app->baseDir));
$app->run();